name: Reuseable Workflow
on:
  workflow_call:
    inputs:
      arguments:
        description: 'Client JSON Payload'
        type: string
        default: '{}'
        required: true
jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
