name: Reuseable Workflow
on:
  workflow_call:
    inputs:
      arguments:
        description: 'Client JSON Payload'
        type: string
        default: '{}'
        required: false
jobs:
  checkout:
    continue-on-error: true 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
